---
- name: set hostname
  nxos_system:
    hostname: "{{ inventory_hostname }}"

- name: set nameserver
  nxos_system:
    name_servers: "{{ hostvars[inventory_hostname].dns }}"
  when: hostvars[inventory_hostname].dns != None

- name: enable features
  nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: "{{ hostvars[inventory_hostname].features }}"
