- name: remove vlan
  nxos_vlan:
    vlan_id: "{{ item }}"
    state: absent
  loop: "{{ remove['ansible_facts']['vlans'] }}"

- name: remove vni configuration (vtep)
  nxos_vxlan_vtep_vni:
    interface: nve1
    vni: "200{{ item }}"
    state: absent
  loop: "{{ remove['ansible_facts']['vlans'] }}"

- name: remove vni configuration (evpn)
  nxos_evpn_vni:
    vni: "200{{ item }}"
    state: absent
  loop: "{{ remove['ansible_facts']['vlans'] }}"
