---
- name: adding application profile
  aci_ap:
    validate_certs: no
    hostname: "{{ inventory_hostname }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    tenant: "{{ TENANT_NAME }}"
    ap: "{{ AP_NAME }}"
