---
- name: apt-update
  apt:
    update_cache: "yes"

- name: install apache
  apt:
    name: apache2

- name: ensure apache is running
  service:
    name: apache2
    state: started

- name: remove old index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: copy new website
  copy:
    src: ../files/
    dest: /var/www/html/